import axios from 'axios'
import { getSession } from 'next-auth/react'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import About from '../components/About'
import Homee from '../components/Home'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import Testimonials from '../components/Testimonials'
import useMediaQuery from '../hooks/MediaQuery'
import { setFontSize, setMyData, setMyProjects, setTechnologies } from '../state/index'

export default function Home({session, mydata , myprojects , technologies}) {
  const dispatch = useDispatch()
  const background = useSelector(state => state.background)

  const isAboveMediumScreens = useMediaQuery("(min-width:800px)")

  useEffect(() => {
    dispatch(setMyData(mydata))
    dispatch(setMyProjects(myprojects))
    dispatch(setTechnologies(technologies))
    }, [])

    console.log(session)

    useEffect(()=>{
      dispatch(setFontSize({
        xs: isAboveMediumScreens ? '12px' : '10px',
        sm: isAboveMediumScreens ? '14px' : '12px',
        base: isAboveMediumScreens ? '16px' : '14px',
        lg: isAboveMediumScreens ? '18px' : '16px',
        xl: isAboveMediumScreens ? '20px' : '18px',
        xxl: isAboveMediumScreens ? '24px' : '20px',
        xxxl: isAboveMediumScreens ? '30px' : '24px',
        xxxxl: isAboveMediumScreens ? '36px' : '28px',
        xxxxxl: isAboveMediumScreens ? '48px' : '32px',
        xxxxxxl: isAboveMediumScreens ? '64px' : '36px',
       }))
    } , [isAboveMediumScreens])
  
 
  return (
    <div>
      <Head>
        <title>SinghKuldeep - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpg" />
      </Head>

    <main style={{background:background.secondary}}> 
      <Homee/>
      <Projects/>
      <Skills/>
      <About/>
      <Testimonials/>
    
     </main>
    
    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context)

 const data = await Promise.all(["a8da2365-f7a2-4e3b-9e3e-6d90071e663e", "38211ee0-3732-4738-b823-708ccd34bcf9"].map( async(projectId) => {
   const { data } = await axios.get(`${process.env.NEXTAUTH_URL}/api/project/${projectId}`)
   return data
 })
)

  const mydetails = await axios.get(`${process.env.NEXTAUTH_URL}/api/mydetails`)
  const technologies = await axios.get(`${process.env.NEXTAUTH_URL}/api/technologies`)

  return {
    props: {
      session,
      mydata : mydetails.data,
      myprojects:data,
      technologies:technologies.data
    }
  }
}
