import Head from 'next/head'
import Navbar from '../components/Navbar'
import Homee from '../components/Home'
import { useSelector } from 'react-redux'
import { useEffect, useState } from 'react'
import {client} from '../sanity.cli'
import { useDispatch } from 'react-redux'
import { setMyData, setMyProjects } from '../state/index' 
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import About from '../components/About'
import Contact from '../components/Contact'

export default function Home({mydata , myprojects}) {
  const dispatch = useDispatch()
  const theme = useSelector(state => state.theme)

  const [isTopOfPage , setIsTopOfPage] = useState(true)

  useEffect(() => {

    dispatch(setMyData(mydata))
    dispatch(setMyProjects(myprojects))
    const handleScroll = () => {
      if(window.scrollY === 0){
        setIsTopOfPage(true)
      }
      if(window.scrollY !== 0) setIsTopOfPage(false)
    }
    window.addEventListener("scroll" , handleScroll)
    return () => window.removeEventListener("scroll" , handleScroll)
    }, [])
  
 
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main style={{background:`${theme.background}`}}> 
      <Navbar isTopOfPage={isTopOfPage}/>
      <Homee/>
      <Projects/>
      <Skills/>
      <About/>
      <Contact/>
     </main>
    
    </div>
  )
}

export async function getServerSideProps(context) {

  const mydetails = `*[_type == 'mydetails']`
  const projects = `*[_type == 'projects']`
  const mydata = await client.fetch(mydetails)
  const myprojects = await client.fetch(projects)

  return {
    props: {
      mydata,
      myprojects
    }, 
  }
}
